// ─────────────────────────────────────────────────────────────────
// FICHIER CENTRAL DES TAGS
// Modifie ici pour changer les couleurs partout sur le site
//
// pillBg    → fond de la pill/tag
// pillText  → texte de la pill/tag
// cardBg    → fond de la carte recette
// cardText  → texte sur la carte recette (si vide, calculé auto)
// ─────────────────────────────────────────────────────────────────

export const TAGS = [
  { key: "vege",
    label: "végé",
    value: "🌿 Végé",
    icon: "herb",
    pillBg:   "#cfff79",
    pillText: "#091718",
    cardBg:   "#091718",
    cardText: "#cfff79",
    cardBorder: "#cfff79",
    actionBg: "#cfff79",}
,
  { key: "poisson",
    label: "poisson",
    value: "🐟 Poisson",
    icon: "fih",
    pillBg:   "#9be7ff",
    pillText: "#03225c",
    cardBg:   "#03225c",
    cardText: "#9be7ff",
    cardBorder: "#38bdf8",
    actionBg: "#9be7ff", 
  },


  { key: "viande",
    label: "viande",
    value: "🥩 Viande",
    icon: "meat",
    pillBg:   "#ffb9e1",
    pillText: "#510312",
    cardBg:   "#510312",
    cardText: "#ffb9e1",
    cardBorder: "#f472b6",
    actionBg: "#ffb9e1",  
  },
  { key: "dessert",
    label: "dessert",
    value: "🍰 Dessert",
    icon: "shortcake",
    pillBg:   "#510312",
    pillText: "#ffb9e1",
    cardBg:   "#ffb9e1",
    cardText: "#510312",
    cardBorder: "#510312",
    actionBg: "#510312", 
  },
  {
    key: "italien",
    label: "italien",
    value: "🍝 Italien",
    icon: "pasta",
    pillBg:   "#091718",
    pillText: "#cfff79",
    cardBg:   "#cfff79",
    cardText: "#1a3d1a",
    cardBorder: "#091718",
    actionBg: "#091718", 
  },
  
  { key: "asiatique",
    label: "asiatique",
    value: "🥢 Asiatique",
    icon: "chopsticks",
    pillBg:   "#510312",
    pillText: "#ffffff",
    cardBg:   "#f87171",
    cardText: "#510312",
    cardBorder: "#510312",
    actionBg: "#510312", 
  },
  { key: "francais",
    label: "français",
    value: "🇫🇷 Français",
    icon: "cheese",
    pillBg:   "#03225c",
    pillText: "#ffffff",
    cardBg:   "#ffffff",
    cardText: "#111111",
    cardBorder: "#03225c",
    actionBg: "#03225c", 
  },
  { key: "oriental",
    label: "oriental",
    value: "🧆 Oriental",
    icon: "falafel",
    pillBg:   "#510312",
    pillText: "#fe7c3e",
    cardBg:   "#fe7c3e",
    cardText: "#510312",
    cardBorder: "#510312",
    actionBg: "#510312", 
  },
  { key: "economique",
    label: "économique",
    value: "💰 Économique",
    icon: "money",
    pillBg:   "#00261e",
    pillText: "#3dff8e",
    cardBg:   "#3dff8e",
    cardText: "#00261e",
    cardBorder: "#00261e",
    actionBg: "#00261e", 
  },
  { key: "leger",
    label: "léger",
    value: "🥗 Léger",
    icon: "feather",
    pillBg:   "#03225c",
    pillText: "#9be7ff",
    cardBg:   "#9be7ff",
    cardText: "#03225c",
    cardBorder: "#38bdf8",
    actionBg: "#03225c", 
  },
  { key: "rapide",
    label: "rapide",
    value: "⚡ Rapide",
    icon: "eclair",
    pillBg:   "#fffac2",
    pillText: "#ffb000",
    cardBg:   "#ffb000",
    cardText: "#fffac2",
    cardBorder: "#ffb000",
    actionBg: "#fffac2", 
  },
  { key: "proteine",
    label: "protéiné",
    value: "💪 Protéiné",
    icon: "biceps",
    pillBg:   "#d57bff",
    pillText: "#130b2d",
    cardBg:   "#130b2d",
    cardText: "#d57bff",
    cardBorder: "#130b2d",
    actionBg: "#130b2d", 
  },
  { key: "sansfour",
    label: "sans-four",
    value: "🔥 Sans-four",
    icon: "fire",
    pillBg:   "#130b2d",
    pillText: "#d57bff",
    cardBg:   "#d57bff",
    cardText: "#130b2d",
    cardBorder: "#130b2d",
    actionBg: "#130b2d", 
  },
  { key: "sansgluten",
    label: "sans gluten",
    value: "🌾 Sans gluten",
    icon: "ble",
    pillBg:   "#ffb000",
    pillText: "#fffac2",
    cardBg:   "#fffac2",
    cardText: "#ffb000",
    cardBorder: "#ffb000",
    actionBg: "#ffb000", 
  },
]

// Couleur de carte par défaut si aucun tag principal
export const DEFAULT_CARD_BG   = "#2d2d2d"
export const DEFAULT_CARD_TEXT   = "#ffffff"
export const DEFAULT_CARD_BORDER = "#444444"

// Couleur du bouton "toutes"
export const FILTER_ALL_BG   = "#fe7c3e"
export const FILTER_ALL_TEXT = "#510312"