// ─────────────────────────────────────────────────────────────────
// FICHIER CENTRAL DES TAGS
// Modifie ici pour changer les couleurs partout sur le site
//
// pillBg    → fond de la pill/tag
// pillText  → texte de la pill/tag
// cardBg    → fond de la carte recette
// cardText  → texte sur la carte recette (si vide, calculé auto)
// ─────────────────────────────────────────────────────────────────

export const TAGS = [
  { key: "vege",
    label: "végé",
    value: "vege",
    icon: "herb",
    pillBg:   "#cfff79",
    pillText: "#091718",
    cardBg:   "#091718",
    cardText: "#cfff79",
    cardBorder: "#cfff79",
    actionBg: "#cfff79",}
,
  { key: "poisson",
    label: "poisson",
    value: "poisson",
    icon: "fih",
    pillBg:   "#9be7ff",
    pillText: "#03225c",
    cardBg:   "#03225c",
    cardText: "#9be7ff",
    cardBorder: "#38bdf8",
    actionBg: "#9be7ff", 
  },


  { key: "viande",
    label: "viande",
    value: "viande",
    icon: "meat",
    pillBg:   "#ffb9e1",
    pillText: "#510312",
    cardBg:   "#510312",
    cardText: "#ffb9e1",
    cardBorder: "#f472b6",
    actionBg: "#ffb9e1",  
  },
  { key: "dessert",
    label: "dessert",
    value: "dessert",
    icon: "shortcake",
    pillBg:   "#510312",
    pillText: "#ffb9e1",
    cardBg:   "#ffb9e1",
    cardText: "#510312",
    cardBorder: "#510312",
    actionBg: "#510312", 
  },
  {
    key: "italien",
    label: "italien",
    value: "italien",
    icon: "pasta",
    pillBg:   "#091718",
    pillText: "#cfff79",
    cardBg:   "#cfff79",
    cardText: "#1a3d1a",
    cardBorder: "#091718",
    actionBg: "#091718", 
  },
  
  { key: "asiatique",
    label: "asiatique",
    value: "asiatique",
    icon: "chopsticks",
    pillBg:   "#510312",
    pillText: "#ffffff",
    cardBg:   "#f87171",
    cardText: "#510312",
    cardBorder: "#510312",
    actionBg: "#510312", 
  },
  { key: "francais",
    label: "français",
    value: "francais",
    icon: "cheese",
    pillBg:   "#03225c",
    pillText: "#ffffff",
    cardBg:   "#ffffff",
    cardText: "#03225c",
    cardBorder: "#03225c",
    actionBg: "#03225c", 
  },
  { key: "oriental",
    label: "oriental",
    value: "oriental",
    icon: "falafel",
    pillBg:   "#510312",
    pillText: "#fe7c3e",
    cardBg:   "#fe7c3e",
    cardText: "#510312",
    cardBorder: "#510312",
    actionBg: "#510312", 
  },
  { key: "economique",
    label: "économique",
    value: "economique",
    icon: "money",
    pillBg:   "#00261e",
    pillText: "#3dff8e",
    cardBg:   "#3dff8e",
    cardText: "#00261e",
    cardBorder: "#00261e",
    actionBg: "#00261e", 
  },
  { key: "leger",
    label: "léger",
    value: "leger",
    icon: "feather",
    pillBg:   "#03225c",
    pillText: "#9be7ff",
    cardBg:   "#9be7ff",
    cardText: "#03225c",
    cardBorder: "#38bdf8",
    actionBg: "#03225c", 
  },
  { key: "rapide",
    label: "rapide",
    value: "rapide",
    icon: "eclair",
    pillBg:   "#E49300",
    pillText: "#FFF4C7",
    cardBg:   "#FFF4C7",
    cardText: "#E49300",
    cardBorder: "#E49300",
    actionBg: "#E49300",  
  },
  { key: "proteine",
    label: "protéiné",
    value: "proteine",
    icon: "biceps",
    pillBg:   "#d57bff",
    pillText: "#130b2d",
    cardBg:   "#130b2d",
    cardText: "#d57bff",
    cardBorder: "#d57bff",
    actionBg: "#d57bff",
  },
  { key: "sansfour",
    label: "sans-four",
    value: "sansfour",
    icon: "fire",
    pillBg:   "#130b2d",
    pillText: "#d57bff",
    cardBg:   "#d57bff",
    cardText: "#130b2d",
    cardBorder: "#130b2d",
    actionBg: "#130b2d", 
  },
  { key: "sansgluten",
    label: "sans gluten",
    value: "sansgluten",
    icon: "ble",
    pillBg:   "#FFF4C7",
    pillText: "#E49300",
    cardBg:   "#E49300",
    cardText: "#FFF4C7",
    cardBorder: "#FFF4C7",
    actionBg: "#FFF4C7",
  },
  { key: "bebe",
    label: "bébé",
    value: "bebe",
    icon: "baby",
    pillBg:   "#fce7f3",
    pillText: "#9d174d",
    cardBg:   "#9d174d",
    cardText: "#fce7f3",
    cardBorder: "#fbcfe8",
    actionBg: "#fce7f3",
  },
]

// ─────────────────────────────────────────────────────────────────
// Tags spécifiques à la catégorie "glaces"
// ─────────────────────────────────────────────────────────────────
export const GLACE_TAGS = [
  { key: "lactee",
    label: "avec lait",
    value: "lactee",
    icon: "milk",
    pillBg:   "#fde68a",
    pillText: "#78350f",
    cardBg:   "#78350f",
    cardText: "#fde68a",
    cardBorder: "#fde68a",
    actionBg: "#fde68a",
  },
  { key: "vegetale",
    label: "sans lait",
    value: "vegetale",
    icon: "herb",
    pillBg:   "#cfff79",
    pillText: "#091718",
    cardBg:   "#091718",
    cardText: "#cfff79",
    cardBorder: "#cfff79",
    actionBg: "#cfff79",
  },
  { key: "proteinee",
    label: "protéinée",
    value: "proteinee",
    icon: "biceps",
    pillBg:   "#d57bff",
    pillText: "#130b2d",
    cardBg:   "#130b2d",
    cardText: "#d57bff",
    cardBorder: "#d57bff",
    actionBg: "#d57bff",
  },
  { key: "fruitee",
    label: "aux fruits",
    value: "fruitee",
    icon: "fruit",
    pillBg:   "#9be7ff",
    pillText: "#03225c",
    cardBg:   "#03225c",
    cardText: "#9be7ff",
    cardBorder: "#9be7ff",
    actionBg: "#9be7ff",
  },
]

// ─────────────────────────────────────────────────────────────────
// Tags spécifiques à la catégorie "boissons & cocktails"
// ─────────────────────────────────────────────────────────────────
export const BOISSON_TAGS = [
  { key: "alcoolise",
    label: "alcoolisé",
    value: "alcoolise",
    icon: "alcool",
    pillBg:   "#fde68a",
    pillText: "#78350f",
    cardBg:   "#78350f",
    cardText: "#fde68a",
    cardBorder: "#fde68a",
    actionBg: "#fde68a",
  },
  { key: "sansalcool",
    label: "sans alcool",
    value: "sansalcool",
    icon: "noalcool",
    pillBg:   "#cfff79",
    pillText: "#091718",
    cardBg:   "#091718",
    cardText: "#cfff79",
    cardBorder: "#cfff79",
    actionBg: "#cfff79",
  },
  { key: "sanssucre",
    label: "sans sucre",
    value: "sanssucre",
    icon: "nosugar",
    pillBg:   "#e9d5ff",
    pillText: "#581c87",
    cardBg:   "#581c87",
    cardText: "#e9d5ff",
    cardBorder: "#d8b4fe",
    actionBg: "#e9d5ff",
  },
  { key: "fruite",
    label: "fruité",
    value: "fruite",
    icon: "fruit",
    pillBg:   "#ffb9e1",
    pillText: "#510312",
    cardBg:   "#510312",
    cardText: "#ffb9e1",
    cardBorder: "#ffb9e1",
    actionBg: "#ffb9e1",
  },
  { key: "petillant",
    label: "pétillant",
    value: "petillant",
    icon: "fizz",
    pillBg:   "#9be7ff",
    pillText: "#03225c",
    cardBg:   "#03225c",
    cardText: "#9be7ff",
    cardBorder: "#9be7ff",
    actionBg: "#cffafe",
  },
]

// Tous les tags, toutes catégories confondues (pour les lookups d'affichage)
export const ALL_TAGS = [...TAGS, ...GLACE_TAGS, ...BOISSON_TAGS]

// ─────────────────────────────────────────────────────────────────
// Catégories de recettes : chacune a son propre jeu de tags
// ─────────────────────────────────────────────────────────────────
export const CATEGORIES = {
  recette: { key: "recette", label: "mes recettes",        itemLabel: "recette", icon: "book",     path: "/recipes",  tags: TAGS },
  glace:   { key: "glace",   label: "glaces",              itemLabel: "glace",   icon: "icecream", path: "/glaces",   tags: GLACE_TAGS },
  boisson: { key: "boisson", label: "boissons & cocktails", itemLabel: "boisson", icon: "drink",    path: "/boissons", tags: BOISSON_TAGS },
}

// Détermine la catégorie d'une recette à partir de son tag principal
export function getRecipeCategory(primaryTag, tags) {
  if (GLACE_TAGS.some(t => t.key === primaryTag)) return "glace"
  if (BOISSON_TAGS.some(t => t.key === primaryTag)) return "boisson"
  // Fallback : regarder dans le tableau tags si primary_tag absent
  if (!primaryTag && Array.isArray(tags)) {
    if (GLACE_TAGS.some(t => tags.includes(t.key))) return "glace"
    if (BOISSON_TAGS.some(t => tags.includes(t.key))) return "boisson"
    // Si les tags contiennent des ingrédients cocktail → boisson
    const cocktailKeys = new Set(COCKTAIL_INGREDIENTS.map(i => i.key))
    if (tags.some(t => cocktailKeys.has(t))) return "boisson"
  }
  return "recette"
}

// Couleur de carte par défaut si aucun tag principal
export const DEFAULT_CARD_BG   = "#2d2d2d"
export const DEFAULT_CARD_TEXT   = "#ffffff"
export const DEFAULT_CARD_BORDER = "#444444"

// Couleur de carte pour les boissons & cocktails (neutre, indépendant du tag)
export const BOISSON_CARD_BG     = "#EDE8DF"
export const BOISSON_CARD_BORDER  = "#C8BFB5"
export const BOISSON_CARD_TEXT    = "#1E1E1E"
export const BOISSON_CARD_ACTION  = "rgba(0,0,0,0.07)"

// Couleur du bouton "toutes"
export const FILTER_ALL_BG   = "#fe7c3e"
export const FILTER_ALL_TEXT = "#510312"

// ─────────────────────────────────────────────────────────────────
// Catégories d'ingrédients cocktail (inspiré Difford's Guide, en français)
// ─────────────────────────────────────────────────────────────────
export const COCKTAIL_INGREDIENT_CATEGORIES = {
  spiritueux: { label: "spiritueux de base", color: "#92400e", bg: "#fde68a" },
  liqueur:    { label: "liqueur",            color: "#5b21b6", bg: "#ede9fe" },
  vin:        { label: "vin & vermouth",     color: "#991b1b", bg: "#fee2e2" },
  biere:      { label: "bière & cidre",      color: "#78350f", bg: "#fef3c7" },
  amers:      { label: "amers & bitter",     color: "#14532d", bg: "#cfff79" },
  sirop:      { label: "sirops",             color: "#581c87", bg: "#e9d5ff" },
  jus:        { label: "jus",               color: "#14532d", bg: "#bbf7d0" },
  mixeur:     { label: "mixeurs",            color: "#0c4a6e", bg: "#bae6fd" },
  frigo:      { label: "frigo & placard",    color: "#03225c", bg: "#9be7ff" },
}

// ─────────────────────────────────────────────────────────────────
// Catalogue d'ingrédients cocktail — pour le Cocktail Finder
// Stockés dans tags[] des recettes boisson au moment de la sauvegarde
// ─────────────────────────────────────────────────────────────────
export const COCKTAIL_INGREDIENTS = [
  // Spiritueux de base
  { key: "rhum_blanc",        label: "Rhum blanc",            category: "spiritueux" },
  { key: "rhum_ambre",        label: "Rhum ambré",            category: "spiritueux" },
  { key: "rhum_brun",         label: "Rhum brun",             category: "spiritueux" },
  { key: "rhum_brun_jamaique",label: "Rhum brun jamaïcain",   category: "spiritueux" },
  { key: "rhum_jamaique_ambre",label: "Rhum jamaïcain ambré", category: "spiritueux" },
  { key: "rhum_cubain",       label: "Rhum cubain",           category: "spiritueux" },
  { key: "rhum_overproof",    label: "Rhum overproof",        category: "spiritueux" },
  { key: "rhum_epice",        label: "Rhum épicé",            category: "spiritueux" },
  { key: "cachaca",           label: "Cachaça",               category: "spiritueux" },
  { key: "vodka",             label: "Vodka",                 category: "spiritueux" },
  { key: "gin",               label: "Gin London Dry",        category: "spiritueux" },
  { key: "gin_contemp",       label: "Gin contemporain",      category: "spiritueux" },
  { key: "tequila_blanche",   label: "Tequila blanche",       category: "spiritueux" },
  { key: "tequila_reposado",  label: "Tequila reposado",      category: "spiritueux" },
  { key: "mezcal",            label: "Mezcal",                category: "spiritueux" },
  { key: "whisky",            label: "Whisky écossais",       category: "spiritueux" },
  { key: "scotch",            label: "Scotch",                category: "spiritueux" },
  { key: "irish_whiskey",     label: "Irish Whiskey",         category: "spiritueux" },
  { key: "whisky_japonais",   label: "Whisky japonais",       category: "spiritueux" },
  { key: "bourbon",           label: "Bourbon américain",     category: "spiritueux" },
  { key: "rye",               label: "Rye whiskey",           category: "spiritueux" },
  { key: "cognac",            label: "Cognac",                category: "spiritueux" },
  { key: "cognac_vsop",       label: "Cognac VSOP",           category: "spiritueux" },
  { key: "calvados",          label: "Calvados",              category: "spiritueux" },
  { key: "pisco",             label: "Pisco",                 category: "spiritueux" },
  { key: "brandy",            label: "Brandy",                category: "spiritueux" },
  // Liqueurs
  { key: "cointreau",         label: "Cointreau",             category: "liqueur" },
  { key: "triple_sec",        label: "Triple Sec",            category: "liqueur" },
  { key: "grand_marnier",     label: "Grand Marnier",         category: "liqueur" },
  { key: "amaretto",          label: "Amaretto",              category: "liqueur" },
  { key: "kahlua",            label: "Kahlúa",                category: "liqueur" },
  { key: "liqueur_cafe",      label: "Liqueur de café",       category: "liqueur" },
  { key: "baileys",           label: "Baileys",               category: "liqueur" },
  { key: "limoncello",        label: "Limoncello",            category: "liqueur" },
  { key: "maraschino",        label: "Maraschino Luxardo",    category: "liqueur" },
  { key: "chartreuse_verte",  label: "Chartreuse verte",      category: "liqueur" },
  { key: "chartreuse_jaune",  label: "Chartreuse jaune",      category: "liqueur" },
  { key: "st_germain",        label: "St-Germain",            category: "liqueur" },
  { key: "creme_cassis",      label: "Crème de cassis",       category: "liqueur" },
  { key: "creme_mure",        label: "Crème de mûre",         category: "liqueur" },
  { key: "creme_menthe",      label: "Crème de menthe",       category: "liqueur" },
  { key: "creme_cacao_blanc", label: "Crème de cacao blanche",category: "liqueur" },
  { key: "creme_cacao_brun",  label: "Crème de cacao brune",  category: "liqueur" },
  { key: "creme_violette",    label: "Crème de violette",     category: "liqueur" },
  { key: "apricot_brandy",    label: "Apricot Brandy",        category: "liqueur" },
  { key: "midori",            label: "Midori",                category: "liqueur" },
  { key: "curacao_bleu",      label: "Curaçao bleu",          category: "liqueur" },
  { key: "malibu",            label: "Malibu",                category: "liqueur" },
  { key: "passoa",            label: "Passoã",                category: "liqueur" },
  { key: "southern_comfort",  label: "Southern Comfort",      category: "liqueur" },
  { key: "drambuie",          label: "Drambuie",              category: "liqueur" },
  { key: "benedictine",       label: "Bénédictine",           category: "liqueur" },
  { key: "licor_43",          label: "Licor 43",              category: "liqueur" },
  { key: "jagermeister",      label: "Jägermeister",          category: "liqueur" },
  { key: "absinthe",          label: "Absinthe",              category: "liqueur" },
  { key: "absinthe_rouge",    label: "Absinthe rouge",        category: "liqueur" },
  { key: "frangelico",        label: "Frangelico",            category: "liqueur" },
  { key: "allspice_dram",     label: "Allspice Dram",         category: "liqueur" },
  { key: "creme_banane",      label: "Crème de banane",       category: "liqueur" },
  { key: "creme_coco_liq",    label: "Crème de noix de coco",category: "liqueur" },
  { key: "galliano",          label: "Galliano",              category: "liqueur" },
  { key: "chambord",          label: "Chambord",              category: "liqueur" },
  { key: "pimms",             label: "Pimm's No.1",           category: "liqueur" },
  { key: "punsch",            label: "Punsch",                category: "liqueur" },
  // Vin & Vermouth
  { key: "champagne",         label: "Champagne",             category: "vin" },
  { key: "prosecco",          label: "Prosecco",              category: "vin" },
  { key: "vin_blanc",         label: "Vin blanc sec",         category: "vin" },
  { key: "vin_rouge",         label: "Vin rouge",             category: "vin" },
  { key: "vermouth_dry",      label: "Vermouth dry",          category: "vin" },
  { key: "vermouth_rouge",    label: "Vermouth rouge",        category: "vin" },
  { key: "porto",             label: "Porto rouge",           category: "vin" },
  { key: "sherry",            label: "Sherry",                category: "vin" },
  // Bière & Cidre
  { key: "biere_blonde",      label: "Bière blonde",          category: "biere" },
  { key: "biere_brune",       label: "Bière brune",           category: "biere" },
  { key: "ginger_beer",       label: "Ginger beer",           category: "biere" },
  { key: "cidre",             label: "Cidre",                 category: "biere" },
  // Amers & Bitter
  { key: "angostura",         label: "Angostura bitters",     category: "amers" },
  { key: "peychauds",         label: "Peychaud's bitters",    category: "amers" },
  { key: "peach_bitters",     label: "Peach Bitters",         category: "amers" },
  { key: "orange_bitters",    label: "Orange bitters",        category: "amers" },
  { key: "campari",           label: "Campari",               category: "amers" },
  { key: "aperol",            label: "Aperol",                category: "amers" },
  { key: "suze",              label: "Suze",                  category: "amers" },
  { key: "pastis",            label: "Pastis",                category: "amers" },
  { key: "ricard",            label: "Ricard",                category: "amers" },
  { key: "amaro_montenegro",  label: "Amaro Montenegro",      category: "amers" },
  { key: "amaro_nonino",      label: "Amaro Nonino",          category: "amers" },
  { key: "fernet",            label: "Fernet-Branca",         category: "amers" },
  // Sirops
  { key: "sirop_sucre",       label: "Sirop de sucre",        category: "sirop" },
  { key: "canadou",           label: "Canadou",               category: "sirop" },
  { key: "sirop_agave",       label: "Sirop d'agave",         category: "sirop" },
  { key: "grenadine",         label: "Grenadine",             category: "sirop" },
  { key: "sirop_orgeat",      label: "Sirop d'orgeat",        category: "sirop" },
  { key: "falernum",          label: "Falernum",              category: "sirop" },
  { key: "sirop_passion",     label: "Sirop de fruit de la passion", category: "sirop" },
  { key: "sirop_peche",       label: "Sirop de pêche",        category: "sirop" },
  { key: "sirop_framboise",   label: "Sirop de framboise",    category: "sirop" },
  { key: "sirop_menthe",      label: "Sirop de menthe",       category: "sirop" },
  { key: "sirop_vanille",     label: "Sirop de vanille",      category: "sirop" },
  { key: "sirop_coco",        label: "Sirop de coco",         category: "sirop" },
  { key: "sirop_cannelle",    label: "Sirop de cannelle",     category: "sirop" },
  { key: "sirop_gingembre",   label: "Sirop de gingembre",    category: "sirop" },
  { key: "miel",              label: "Miel",                  category: "sirop" },
  { key: "sirop_erable",      label: "Sirop d'érable",        category: "sirop" },
  // Jus & Purées
  { key: "jus_citron",        label: "Jus de citron frais",   category: "jus" },
  { key: "jus_citron_vert",   label: "Jus de citron vert",    category: "jus" },
  { key: "jus_orange",        label: "Jus d'orange",          category: "jus" },
  { key: "jus_ananas",        label: "Jus d'ananas",          category: "jus" },
  { key: "jus_cranberry",     label: "Jus de cranberry",      category: "jus" },
  { key: "jus_pamplemousse",  label: "Jus de pamplemousse",   category: "jus" },
  { key: "jus_passion",       label: "Jus de fruit de la passion", category: "jus" },
  { key: "jus_mangue",        label: "Jus de mangue",         category: "jus" },
  { key: "jus_peche",         label: "Jus de pêche",          category: "jus" },
  { key: "jus_pomme",         label: "Jus de pomme",          category: "jus" },
  { key: "jus_tomate",        label: "Jus de tomate",         category: "jus" },
  { key: "jus_goyave",        label: "Jus de goyave",         category: "jus" },
  { key: "manzana",           label: "Manzana",               category: "liqueur" },
  { key: "puree_peche",       label: "Purée de pêche blanche",category: "jus" },
  { key: "puree_fraise",      label: "Purée de fraise",       category: "jus" },
  { key: "puree_framboise",   label: "Purée de framboise",    category: "jus" },
  { key: "puree_passion",     label: "Purée de passion",      category: "jus" },
  // Mixeurs & sodas
  { key: "tonic",             label: "Tonic water",           category: "mixeur" },
  { key: "eau_gazeuse",       label: "Eau gazeuse",           category: "mixeur" },
  { key: "cola",              label: "Cola",                  category: "mixeur" },
  { key: "ginger_ale",        label: "Ginger ale",            category: "mixeur" },
  { key: "limonade",          label: "Limonade",              category: "mixeur" },
  { key: "soda_citron",       label: "Soda citron-lime",      category: "mixeur" },
  { key: "red_bull",          label: "Red Bull",              category: "mixeur" },
  { key: "eau_coco",          label: "Eau de coco",           category: "mixeur" },
  { key: "lait_coco",         label: "Lait de coco",          category: "mixeur" },
  // Frigo & Placard — fruits frais
  { key: "citron_fruit",      label: "Citron (fruit)",        category: "frigo" },
  { key: "citron_vert_fruit", label: "Citron vert (fruit)",   category: "frigo" },
  { key: "orange_fruit",      label: "Orange (fruit)",        category: "frigo" },
  { key: "pamplemousse_fruit",label: "Pamplemousse (fruit)",  category: "frigo" },
  { key: "ananas_frais",      label: "Ananas frais",          category: "frigo" },
  { key: "fraises",           label: "Fraises",               category: "frigo" },
  { key: "framboises",        label: "Framboises",            category: "frigo" },
  { key: "mures",             label: "Mûres",                 category: "frigo" },
  { key: "fruits_passion",    label: "Fruits de la passion",  category: "frigo" },
  // Frigo & Placard — herbes & épices
  { key: "menthe_fraiche",    label: "Menthe fraîche",        category: "frigo" },
  { key: "concombre",         label: "Concombre",             category: "frigo" },
  { key: "gingembre",         label: "Gingembre frais",       category: "frigo" },
  { key: "celeri",            label: "Branche de céleri",     category: "frigo" },
  { key: "cannelle",          label: "Cannelle",              category: "frigo" },
  { key: "noix_muscade",      label: "Noix de muscade",       category: "frigo" },
  // Frigo & Placard — garnitures
  { key: "zeste_citron",      label: "Zeste de citron",       category: "frigo" },
  { key: "zeste_orange",      label: "Zeste d'orange",        category: "frigo" },
  { key: "tranche_citron",    label: "Tranche de citron",     category: "frigo" },
  { key: "tranche_orange",    label: "Tranche d'orange",      category: "frigo" },
  { key: "quartier_citron_vert", label: "Quartier de citron vert", category: "frigo" },
  { key: "tranche_pomme",     label: "Tranche de pomme",      category: "frigo" },
  { key: "cerises_marasquin", label: "Cerises Marasquin",     category: "frigo" },
  { key: "cerises_amarena",   label: "Cerises Amarena",       category: "frigo" },
  { key: "olives",            label: "Olives vertes",         category: "frigo" },
  // Frigo & Placard — base & assaisonnements
  { key: "blanc_oeuf",        label: "Blanc d'œuf",           category: "frigo" },
  { key: "creme_fraiche",     label: "Crème fraîche",         category: "frigo" },
  { key: "lait",              label: "Lait",                  category: "frigo" },
  { key: "sucre",             label: "Sucre blanc",           category: "frigo" },
  { key: "cassonade",         label: "Cassonade",             category: "frigo" },
  { key: "sel",               label: "Sel",                   category: "frigo" },
  { key: "sel_celeri",        label: "Sel de céleri",         category: "frigo" },
  { key: "poivre",            label: "Poivre",                category: "frigo" },
  { key: "worcestershire",    label: "Sauce Worcestershire",  category: "frigo" },
  { key: "tabasco",           label: "Tabasco",               category: "frigo" },
  { key: "piment",            label: "Piment",                category: "frigo" },
  { key: "lait_concentre",    label: "Lait concentré sucré",  category: "frigo" },
  { key: "espresso",          label: "Espresso",              category: "frigo" },
  { key: "the_matcha",        label: "Thé matcha",            category: "frigo" },
  { key: "vanille_gousse",    label: "Vanille (gousse)",      category: "frigo" },
  { key: "vanille_extrait",   label: "Vanille (extrait)",     category: "frigo" },
]